# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appletree.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='appletree.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61ppletree.proto\"\x18\n\x04Time\x12\x10\n\x08time_min\x18\x01 \x01(\x05\"$\n\x0eNumberOfApples\x12\x12\n\nnum_apples\x18\x01 \x01(\x05\"5\n\tIntensity\x12(\n\x0fintensity_level\x18\x01 \x01(\x0e\x32\x0f.IntensityLevel*4\n\x0eIntensityLevel\x12\n\n\x06STRONG\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\n\n\x06GENTLE\x10\x02\x32\x37\n\tAppleTree\x12*\n\x0eShakeAppleTree\x12\x05.Time\x1a\x0f.NumberOfApples\"\x00\x62\x06proto3'
)

_INTENSITYLEVEL = _descriptor.EnumDescriptor(
  name='IntensityLevel',
  full_name='IntensityLevel',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STRONG', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GENTLE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=138,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_INTENSITYLEVEL)

IntensityLevel = enum_type_wrapper.EnumTypeWrapper(_INTENSITYLEVEL)
STRONG = 0
MEDIUM = 1
GENTLE = 2



_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_min', full_name='Time.time_min', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=43,
)


_NUMBEROFAPPLES = _descriptor.Descriptor(
  name='NumberOfApples',
  full_name='NumberOfApples',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_apples', full_name='NumberOfApples.num_apples', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=81,
)


_INTENSITY = _descriptor.Descriptor(
  name='Intensity',
  full_name='Intensity',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='intensity_level', full_name='Intensity.intensity_level', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=136,
)

_INTENSITY.fields_by_name['intensity_level'].enum_type = _INTENSITYLEVEL
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['NumberOfApples'] = _NUMBEROFAPPLES
DESCRIPTOR.message_types_by_name['Intensity'] = _INTENSITY
DESCRIPTOR.enum_types_by_name['IntensityLevel'] = _INTENSITYLEVEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:Time)
  })
_sym_db.RegisterMessage(Time)

NumberOfApples = _reflection.GeneratedProtocolMessageType('NumberOfApples', (_message.Message,), {
  'DESCRIPTOR' : _NUMBEROFAPPLES,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:NumberOfApples)
  })
_sym_db.RegisterMessage(NumberOfApples)

Intensity = _reflection.GeneratedProtocolMessageType('Intensity', (_message.Message,), {
  'DESCRIPTOR' : _INTENSITY,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:Intensity)
  })
_sym_db.RegisterMessage(Intensity)



_APPLETREE = _descriptor.ServiceDescriptor(
  name='AppleTree',
  full_name='AppleTree',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=192,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='ShakeAppleTree',
    full_name='AppleTree.ShakeAppleTree',
    index=0,
    containing_service=None,
    input_type=_TIME,
    output_type=_NUMBEROFAPPLES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APPLETREE)

DESCRIPTOR.services_by_name['AppleTree'] = _APPLETREE

# @@protoc_insertion_point(module_scope)
