# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: appletree.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='appletree.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0f\x61ppletree.proto\"\x14\n\x04Time\x12\x0c\n\x04time\x18\x01 \x01(\x05\"!\n\x0b\x41ppleStatus\x12\x12\n\nnum_apples\x18\x01 \x01(\x05\"!\n\x06\x42ucket\x12\x17\n\x0fremaining_space\x18\x01 \x01(\x05\" \n\x05Water\x12\x17\n\x0fwater_in_liters\x18\x01 \x01(\x05\"2\n\nSoilStatus\x12$\n\x0equality_status\x18\x01 \x01(\x0e\x32\x0c.SoilQuality*,\n\x0bSoilQuality\x12\x08\n\x04GOOD\x10\x00\x12\n\n\x06MEDIUM\x10\x01\x12\x07\n\x03\x42\x41\x44\x10\x02\x32s\n\tAppletree\x12\"\n\tGrowApple\x12\x05.Time\x1a\x0c.AppleStatus\"\x00\x12\x1e\n\x08GetApple\x12\x07.Bucket\x1a\x07.Bucket\"\x00\x12\"\n\tWaterTree\x12\x06.Water\x1a\x0b.SoilStatus\"\x00\x62\x06proto3'
)

_SOILQUALITY = _descriptor.EnumDescriptor(
  name='SoilQuality',
  full_name='SoilQuality',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOOD', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BAD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=197,
  serialized_end=241,
)
_sym_db.RegisterEnumDescriptor(_SOILQUALITY)

SoilQuality = enum_type_wrapper.EnumTypeWrapper(_SOILQUALITY)
GOOD = 0
MEDIUM = 1
BAD = 2



_TIME = _descriptor.Descriptor(
  name='Time',
  full_name='Time',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Time.time', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=39,
)


_APPLESTATUS = _descriptor.Descriptor(
  name='AppleStatus',
  full_name='AppleStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_apples', full_name='AppleStatus.num_apples', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=74,
)


_BUCKET = _descriptor.Descriptor(
  name='Bucket',
  full_name='Bucket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='remaining_space', full_name='Bucket.remaining_space', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=109,
)


_WATER = _descriptor.Descriptor(
  name='Water',
  full_name='Water',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='water_in_liters', full_name='Water.water_in_liters', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=143,
)


_SOILSTATUS = _descriptor.Descriptor(
  name='SoilStatus',
  full_name='SoilStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='quality_status', full_name='SoilStatus.quality_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=195,
)

_SOILSTATUS.fields_by_name['quality_status'].enum_type = _SOILQUALITY
DESCRIPTOR.message_types_by_name['Time'] = _TIME
DESCRIPTOR.message_types_by_name['AppleStatus'] = _APPLESTATUS
DESCRIPTOR.message_types_by_name['Bucket'] = _BUCKET
DESCRIPTOR.message_types_by_name['Water'] = _WATER
DESCRIPTOR.message_types_by_name['SoilStatus'] = _SOILSTATUS
DESCRIPTOR.enum_types_by_name['SoilQuality'] = _SOILQUALITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Time = _reflection.GeneratedProtocolMessageType('Time', (_message.Message,), {
  'DESCRIPTOR' : _TIME,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:Time)
  })
_sym_db.RegisterMessage(Time)

AppleStatus = _reflection.GeneratedProtocolMessageType('AppleStatus', (_message.Message,), {
  'DESCRIPTOR' : _APPLESTATUS,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:AppleStatus)
  })
_sym_db.RegisterMessage(AppleStatus)

Bucket = _reflection.GeneratedProtocolMessageType('Bucket', (_message.Message,), {
  'DESCRIPTOR' : _BUCKET,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:Bucket)
  })
_sym_db.RegisterMessage(Bucket)

Water = _reflection.GeneratedProtocolMessageType('Water', (_message.Message,), {
  'DESCRIPTOR' : _WATER,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:Water)
  })
_sym_db.RegisterMessage(Water)

SoilStatus = _reflection.GeneratedProtocolMessageType('SoilStatus', (_message.Message,), {
  'DESCRIPTOR' : _SOILSTATUS,
  '__module__' : 'appletree_pb2'
  # @@protoc_insertion_point(class_scope:SoilStatus)
  })
_sym_db.RegisterMessage(SoilStatus)



_APPLETREE = _descriptor.ServiceDescriptor(
  name='Appletree',
  full_name='Appletree',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=243,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='GrowApple',
    full_name='Appletree.GrowApple',
    index=0,
    containing_service=None,
    input_type=_TIME,
    output_type=_APPLESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetApple',
    full_name='Appletree.GetApple',
    index=1,
    containing_service=None,
    input_type=_BUCKET,
    output_type=_BUCKET,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WaterTree',
    full_name='Appletree.WaterTree',
    index=2,
    containing_service=None,
    input_type=_WATER,
    output_type=_SOILSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_APPLETREE)

DESCRIPTOR.services_by_name['Appletree'] = _APPLETREE

# @@protoc_insertion_point(module_scope)
