# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import appletree_pb2 as appletree__pb2


class AppleTreeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ShakeAppleTree = channel.unary_unary(
                '/AppleTree/ShakeAppleTree',
                request_serializer=appletree__pb2.Time.SerializeToString,
                response_deserializer=appletree__pb2.NumberOfApples.FromString,
                )


class AppleTreeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ShakeAppleTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppleTreeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ShakeAppleTree': grpc.unary_unary_rpc_method_handler(
                    servicer.ShakeAppleTree,
                    request_deserializer=appletree__pb2.Time.FromString,
                    response_serializer=appletree__pb2.NumberOfApples.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AppleTree', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppleTree(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ShakeAppleTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AppleTree/ShakeAppleTree',
            appletree__pb2.Time.SerializeToString,
            appletree__pb2.NumberOfApples.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
